### PR TITLE
Various Features

### LINKED ISSUE #10: tz doesn't update the current time while running
The time does update, but the 24-hour clock on after the time zone does not for shift hours. For example, if you do tz and then look an hour later, the wrong hour is still highlighted.

### LINKED ISSUE #39: Date difference is incorrect when moving between dates
Neat time tool! A hopefully helpful bug report: When launching tz, it will correctly note a date difference (or lack thereof) between different time zones, but when you use arrow keys to move to other times, it will still maintain the date difference established on launch for all other times, even when it should change. See video, which compares US/Central to US/Eastern time zones. Comparing with US/Pacific shows correctly that there is not currently a date difference, but then continues to claim there is never a date difference at any hour.

https://user-images.githubusercontent.com/64038/226516850-e9940b8f-00b4-40fe-a0a3-eea5c8fc7afc.mov

### LINKED ISSUE #40: Interactive keyboard shortcut to jump forwards/backwards a whole day (or more?)
Maybe bind PageUp/PageDown to skip 24 hours ahead/back.

Dunno if the amount moved should be configurable, that's getting close to a whole scheduling thing rather than a quick tool.

### PR DESCRIPTION
**Pull request by wyne**
## Summary
- Fix: Update times as you move
- New: Jump by day with `H` / `L`
- New:Jump by week with `<` / `>`
- New: Add `-w` for watch mode, updating every minute
- New: Right align times for easier reading; add month and year
- New: Press `o` to open in timeanddate.com
- New: Press `t` to go to now

## Demo
Top: Current
Bottom: New

https://github.com/user-attachments/assets/106bb105-92ee-4c99-866e-278d88e366dd

Resolves #39
Resolves #40
Resolves #10

### CODE REVIEW

**Comment by oz** [comment]
Hi!

First, thanks for these changes, and recording a demo. 👍🏻

I really want to merge this, but I see a failing test right now. Something with date change not happening at midnight. I'll take a look later, unless you beat me to it.

**Comment by wyne** [comment]
It's probably my latest commit that resolved a bug where it would skip over a day at midnight (ex: Wed->Fri). So something is off between the UI and the test. 

I'll take a look.

**Comment by wyne** [comment]
I was confused about the distinction between `model.now` and `Now`, so I consolidated the clocks into one unified clock. That made sense to me, but let me know if I'm missing something.

I'm still debugging the test though. I had it working at some point, but still hitting an issue even though it does work correctly in the TUI.

**Comment by wyne** [comment]
Ah, I figured it out in the latest commit. Lmk if you have a better idea.

**Comment by oz** [comment]
> Lmk if you have a better idea. I don't do a lot of go programming :)

Me neither lately. 😞 

Alright. That PR works for me. Thanks a lot! 🙇🏻

**Pull request merged**
